[package]
name = "rough-blockchain-rustlang"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.0"
hex = "0.4.3"
redb = "2.1.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"